### ISSUE TITLE
Docs: Usage instructions could be clearer

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-auth#3]
Current readme looks like this:

```
$ npm install -g @adobe/aio-cli-plugin-auth
$ aio COMMAND
running command...
$ aio (-v|--version|version)
@adobe/aio-cli-plugin-auth/1.0.4 darwin-x64 node-v10.15.3
$ aio --help [COMMAND]
USAGE
  $ aio COMMAND
...
```

We should probably be clearer that this is a plugin for the aio-cli and is auto installed when the aio-cli is.

Usage should maybe go straight to :
```
aio login ...
aio logout ...
...
```

**Comment by shazron** [comment]
I think the main cli will have all the documentation for all the plugins as well. 
For that usage section, we can remove the `<!-- usage -->` section in the README.md if it's confusing.
