### ISSUE TITLE
Enhance output for login and logout

### ISSUE THREAD

**Issue by sarahxxu** [adobe/aio-cli-plugin-auth#30]
**Is your feature request related to a problem? Please describe.**
There's no clear indication of current user's login / logout state. 

**Describe the solution you'd like**

When a user `aio (auth) login` if the user is logged in, the output should be `You are currently logged in, your user access token is xxx`. 

When a user log out `aio (auth) logout` the cli should output a friendly message saying `You are current logged out.`

**Comment by shazron** [comment]
Logout fix: https://github.com/adobe/aio-cli-plugin-auth/commit/9c45c44dc95fbb860e400fb15323a3a889e35ff4

**Comment by purplecabbage** [comment]
Done
