### ISSUE TITLE
`aio logout` does not log the user out (access token still stored in local)

### ISSUE THREAD

**Issue by sarahxxu** [adobe/aio-cli-plugin-auth#32]
**Describe the bug**
```
$ aio login
<access-token>
$ aio logout
```
but after you've supposedly "logged out", the access token is not removed from config (global), so you can still see the user token and refresh token shown in `aio config`

**To Reproduce**

If you are inside a project with a local `.aio`, you can see the access token remove from config after you've logged out, but if you change directory to another folder without a local `.aio`, you can see that the access token is still there in global `.aio`. 
```
$cd project-a
$aio login

$aio config

$aio logout
$aio config

$cd different-directory

$aio config
```
In addition, if you are inside a project with local `.aio`, after you have logged out if you try to type in `aio logout` again, it throws this error. it should really say "You are currently logged out". 
```
$cd project-a
$aio login

$aio config
$aio logout

$aio logout
 ›   Error: Cannot logout context '$cli': Token missing or expired
```

**Expected behavior**
Config should be cleared for both global AND local, and ideally `aio logout` should print a message saying "you are logged out"

**Comment by rajarju** [comment]
This seems to be related https://github.com/adobe/aio-lib-ims/issues/21

**Comment by moritzraho** [comment]
@rajarju here is some more information using `aio config --verbose` while I tried to reproduce the error:
- in folder with a local  .aio: empty global and empty local config
- aio login -> refresh token and access token stored in global .aio but local .aio has now
{
  $ims: {
    $cli: {
      $cli.bare-output: false
    },
    $current: "$cli"
  }
}
- aio logout -> all good removes access token from global config (refresh token is still here as non force option)
- now if I login again here is catch: somehow the refresh token of the global config is now in my local config and in my global config I have a new refresh token and access token
- aio logout: now both config have the same refresh token from the previous local config. No access token in global config anymore
- aio logout --force: the refresh token is removed from the global config but not the local one
- aio logout --force (again): doesn’t remove the local refresh token
