### ISSUE TITLE
[Windows] Cannot logout and login into another account

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli-plugin-auth#34]
### Expected Behaviour
After I logout, I want to be able to login again but with another account.

### Actual Behaviour
After logout, on the second login, in Chrome, I don't have a chance to switch account because it goes too fast. Therefore, I'm logged in again, but with the wrong account.

### Reproduce Scenario (including but not limited to)
Pre-requisite: Working on Windows, with a Chrome browser opening the login page.

#### Steps to Reproduce
- Log into an account using `aio auth login`
- Logout using `aio auth logout`
- Try to log into another account by changing the email address on login page. On Chrome at least, it reuses previous credentials and you should not have the time to switch account.

#### Platform and Version
Windows 10, Node 14 

#### Logs taken while reproducing problem
What happens on subsequent logins: The "you're logged in" page appears nearly immediately.
<img width="1193" alt="1" src="https://user-images.githubusercontent.com/60901087/82591759-acfc5e80-9b54-11ea-9ef6-cd1dbd5bdcce.png">

**Comment by shazron** [comment]
See #32

**Comment by tmathern** [comment]
Removing all cookies fixes the issue, indeed.

**Comment by meryllblanchet** [comment]
Thanks for confirming @tmathern ! 
I don't think that we should do anything else at CLI level. 

While as a CLI user I expect to be logged in automatically if I am logged in from the browser, I still feel it weird to be logged out in the browser if I log out from my CLI.

WDYT?

**Comment by sarahxxu** [comment]
I agree that the user should not be automatically logged out in the browser by default. 

However, it looks like it's not clear (currently) how a user can log out in the current flow without having to manually type in a different URL (experience cloud for instance). Perhaps we should add a logout functionality to the CLI log in UI.

**Comment by meryllblanchet** [comment]
I like the idea, @shazron what about adding a logout link as suggested by @sarahxxu ?

**Comment by meryllblanchet** [comment]
Nope, in the web UI that pops-up to login and then to confirm that the user has successfully logged in.

**Comment by sarahxxu** [comment]
Yes ^ actually -- let's close this topic and do a separate one for UI improvements on this page. I'm connected with our design team to discuss further!
