### ISSUE TITLE
Support specifying non-default browser for login

### ISSUE THREAD

**Issue by justinedelson** [adobe/aio-cli-plugin-auth#62]
**Describe the solution you'd like**

In short...

```
aio auth:login --browser=Firefox
```

**Describe alternatives you've considered**

#61 defines an alternate approach for the same problem (and they're not necessarily mutually exclusive), but given that cli-ux supports specifying a different browser, more literally implementing support for an alternate browser has better IMO ergonomics.

**Comment by purplecabbage** [comment]
closing this in favor of the --no-open flag which will let the user copy/paste the url and open in whatever browser they wish.
Otherwise we would sort of be responsible for making sure all browsers work, and CAN post back which is a lot to verify and potentially a lot of work
