### ISSUE TITLE
getting Oauth token is not valid when creating a new app using app builder

### ISSUE THREAD

**Issue by pawee-del** [adobe/aio-cli-plugin-auth#66]
ran this command in termina : aio app init extlive
but got the below error : 
![image](https://user-images.githubusercontent.com/72118587/161198461-d43345cd-c921-4e6e-a43f-264a75484b89.png)

was following this tutorial by adobe : https://www.youtube.com/watch?v=b6jKxNnXFrk&t=613s

**Comment by shazron** [comment]
Paste the contents of `aio info`

**Comment by pawee-del** [comment]
hi there, as requested, connect of aio info below :


Using local project's @adobe/aio-cli-plugin-asset-compute version 2.0.1


  System:
    OS: macOS 11.6.1
    CPU: (8) x64 Apple M1
    Memory: 21.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: Not Found
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Virtualization:
    Docker: 20.10.12 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 8.2.0

  Proxies:
    http: (not set)
    https: (not set)
  CLI plugins:
    core:
      @adobe/aio-cli 8.2.0
      @adobe/aio-cli-plugin-app 8.5.1
      @adobe/aio-cli-plugin-auth 2.6.0
      @adobe/aio-cli-plugin-certificate 0.3.0
      @adobe/aio-cli-plugin-config 2.3.0
      @adobe/aio-cli-plugin-console 3.4.2
      @adobe/aio-cli-plugin-events 1.1.6
      @adobe/aio-cli-plugin-info 2.1.0
      @adobe/aio-cli-plugin-runtime 5.3.0
      @oclif/plugin-autocomplete 0.3.0
      @oclif/plugin-help 2.2.3
      @oclif/plugin-not-found 2.3.1
      @oclif/plugin-plugins 1.10.11
      @oclif/plugin-warn-if-update-available 1.7.3
    user:
      @adobe/aio-cli-plugin-asset-compute 2.0.1
      @adobe/aio-cli-plugin-cloudmanager 3.0.0
    link:

**Comment by shazron** [comment]
Please reinstall the cli, and run the command again. There have been plugin updates a few days ago that you don't have.
`npm install -g @adobe/aio-cli`

**Comment by pawee-del** [comment]
this is the output, do i now have the latest :

[image: image.png]

**Comment by shazron** [comment]
this should be fixed with the latest cli (run the command I quoted above)
